version: "3.7"
services:
        elk:
                image: sebp/elk
                ports:
                        - "5601:5601"
                        - "9200:9200"
                        - "5044:5044"
