---
- name: Install nginx and upload webpage
  hosts: all
  become: yes

  vars:
          source_file: ./TestSite/index.html
          dest_file: /var/www/html

  tasks:
  - name: Install nginx
    apt: name=nginx state=latest

  - name: Copy site to nginx
    copy: src={{ source_file }} dest={{ dest_file }} mode=0555
    notify: Restart nginx

  - name: Start and enable nginx service
    service: name=nginx state=started enabled=yes


  handlers:
  - name: Restart nginx
    service: name=nginx state=restarted
